import { ReactNode, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, TextInputProps, View, useWindowDimensions } from 'react-native';
import { KeyboardAwareScrollView } from 'react-native-keyboard-controller';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { colors } from '../theme/colors';
import { Icon, IconName } from './Icon';
export function Screen({ children, title, subtitle, back = false, action }: { children: ReactNode; title?: string; subtitle?: string; back?: boolean; action?: ReactNode }) {
  const insets = useSafeAreaInsets(); const { width } = useWindowDimensions();
  return <KeyboardAwareScrollView style={s.screen} bottomOffset={24} keyboardShouldPersistTaps="handled" contentContainerStyle={{ paddingTop: Math.max(insets.top, 16), paddingBottom: Math.max(24, insets.bottom + 18) }}><View style={[s.content, { maxWidth: Math.min(720, width) }]}>
    {(title || back) && <View style={s.heading}><View style={s.headingText}>{back && <Pressable onPress={() => router.back()} style={s.back}><Icon name="back"/></Pressable>}{title && <><Text style={s.title}>{title}</Text>{subtitle && <Text style={s.sub}>{subtitle}</Text>}</>}</View>{action}</View>}{children}
  </View></KeyboardAwareScrollView>;
}
export function Card({ children, style }: { children: ReactNode; style?: object }) { return <View style={[s.card, style]}>{children}</View>; }
export function Button({ label, onPress, icon, variant = 'primary', disabled, loading }: { label: string; onPress: () => void; icon?: IconName; variant?: 'primary' | 'secondary' | 'text' | 'danger'; disabled?: boolean; loading?: boolean }) { return <Pressable accessibilityRole="button" disabled={disabled || loading} onPress={onPress} style={[s.button, variant === 'primary' ? s.primary : variant === 'danger' ? s.danger : variant === 'secondary' ? s.secondary : s.textButton, disabled && { opacity: .5 }]}>{loading ? <ActivityIndicator color={variant === 'primary' ? '#fff' : colors.accent}/> : <>{icon && <Icon name={icon} size={18} color={variant === 'primary' || variant === 'danger' ? '#fff' : colors.accent}/>}<Text style={[s.buttonText, { color: variant === 'primary' || variant === 'danger' ? '#fff' : colors.accent }]}>{label}</Text></>}</Pressable>; }
export function Field({ label, value, onChangeText, error, secureTextEntry, ...props }: TextInputProps & { label: string; value: string; onChangeText: (v: string) => void; error?: string }) { const [visible,setVisible]=useState(false); return <View style={s.field}><Text style={s.label}>{label}</Text><View><TextInput value={value} onChangeText={onChangeText} secureTextEntry={secureTextEntry && !visible} placeholderTextColor="#91A29A" style={[s.input, !!error && { borderColor: colors.danger }, !!secureTextEntry && { paddingRight:52 }]} {...props}/>{!!secureTextEntry && <Pressable accessibilityRole="button" accessibilityLabel={visible?'Hide password':'Show password'} onPress={()=>setVisible(!visible)} style={{position:'absolute',right:0,top:0,bottom:0,width:48,alignItems:'center',justifyContent:'center'}}><Icon name={visible?'eyeOff':'eye'} size={20} color={colors.muted}/></Pressable>}</View>{!!error && <Text style={s.error}>{error}</Text>}</View>; }
export function Chip({ label, selected, onPress }: { label: string; selected?: boolean; onPress?: () => void }) { return <Pressable onPress={onPress} disabled={!onPress} style={[s.chip, selected && s.chipSelected]}><Text style={[s.chipText, selected && { color: colors.accent }]}>{label}</Text></Pressable>; }
export function Row({ title, detail, onPress, icon, right }: { title: string; detail?: string; onPress?: () => void; icon?: IconName; right?: ReactNode }) { return <Pressable onPress={onPress} disabled={!onPress} style={s.row}>{icon && <View style={s.rowIcon}><Icon name={icon} color={colors.accent}/></View>}<View style={{ flex: 1 }}><Text style={s.rowTitle}>{title}</Text>{detail && <Text style={s.rowDetail}>{detail}</Text>}</View>{right || (onPress && <Icon name="chevron" size={18} color={colors.muted}/>)}</Pressable>; }
export function State({ loading, error, empty, retry }: { loading?: boolean; error?: string; empty?: string; retry?: () => void }) { return <View style={s.state}>{loading ? <ActivityIndicator color={colors.accent}/> : <><Text style={s.stateText}>{error || empty}</Text>{error && retry && <Button label="Try again" variant="secondary" onPress={retry}/>}</>}</View>; }
export function Section({ title, action }: { title: string; action?: ReactNode }) { return <View style={s.section}><Text style={s.sectionTitle}>{title}</Text>{action}</View>; }
export function money(value: string | number | undefined, currency = 'INR') { return new Intl.NumberFormat(undefined, { style: 'currency', currency }).format(Number(value || 0)); }
export const s = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.background }, content: { width: '100%', alignSelf: 'center', paddingHorizontal: 20, gap: 16 }, heading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingTop: 10, paddingBottom: 7 }, headingText: { flex: 1 }, back: { marginBottom: 14, width: 40, height: 40, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 10 }, title: { fontSize: 27, lineHeight: 33, fontWeight: '700', color: colors.ink, letterSpacing: -.5 }, sub: { fontSize: 14, color: colors.muted, marginTop: 4 }, card: { backgroundColor: colors.surface, borderRadius: 12, borderWidth: 1, borderColor: colors.border, padding: 16, gap: 12 }, button: { minHeight: 48, paddingHorizontal: 16, borderRadius: 10, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8 }, primary: { backgroundColor: colors.accent }, danger: { backgroundColor: colors.danger }, secondary: { backgroundColor: colors.accentSoft, borderWidth: 1, borderColor: '#C5E2D7' }, textButton: { backgroundColor: 'transparent' }, buttonText: { fontSize: 15, fontWeight: '700' }, field: { gap: 6 }, label: { color: colors.ink, fontSize: 13, fontWeight: '600' }, input: { minHeight: 48, borderWidth: 1, borderColor: colors.border, borderRadius: 10, paddingHorizontal: 13, backgroundColor: colors.surface, color: colors.ink, fontSize: 15 }, error: { color: colors.danger, fontSize: 12 }, chip: { borderWidth: 1, borderColor: colors.border, borderRadius: 8, paddingHorizontal: 11, paddingVertical: 8, backgroundColor: colors.surface }, chipSelected: { borderColor: colors.accent, backgroundColor: colors.accentSoft }, chipText: { color: colors.muted, fontSize: 13, fontWeight: '600' }, row: { flexDirection: 'row', alignItems: 'center', gap: 12, minHeight: 55 }, rowIcon: { width: 40, height: 40, borderRadius: 9, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.accentSoft }, rowTitle: { color: colors.ink, fontSize: 15, fontWeight: '600' }, rowDetail: { color: colors.muted, fontSize: 13, marginTop: 2 }, state: { paddingVertical: 30, alignItems: 'center', gap: 16 }, stateText: { textAlign: 'center', color: colors.muted, fontSize: 14 }, section: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 8 }, sectionTitle: { fontSize: 17, fontWeight: '700', color: colors.ink } });
