import { router, useLocalSearchParams } from 'expo-router';
import * as Print from 'expo-print';
import { useCallback, useEffect, useState } from 'react';
import { Alert, NativeModules, Platform, Text } from 'react-native';
import * as SecureStore from 'expo-secure-store';
import { messageOf, post } from '../../api/client';
import { pos } from '../../api/pos';
import { useLive } from '../../hooks/useLive';
import { useAuth } from '../../store/auth';
import { Button, Card, Field, Row, Screen, Section, State, money } from '../../ui/Kit';
import { colors } from '../../theme/colors';
import type { ReceiptPrinter } from '../../services/printers';
type Snapshot = { number: string; restaurant: { name: string; address: string; phone?: string; currencyCode: string }; order: { id: string; type: string; tableId?: string }; employee: { name: string }; items: { name: string; quantity: number; unitPrice: string }[]; totals: { subtotal: string; tax: string; discount: string; total: string }; payment: { method: string; cashReceived?: string; changeDue?: string }; at: string };
const escapeHtml = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, (ch) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' })[ch] || ch);
export default function ReceiptDetail() {
  const { id } = useLocalSearchParams<{ id: string }>(); const { can } = useAuth();
  const { data, loading, error, refresh } = useLive(useCallback(() => pos.receipt(id), [id]), null as Record<string, unknown> | null, false);
  const [refund, setRefund] = useState(false), [amount, setAmount] = useState(''), [reason, setReason] = useState(''), [busy, setBusy] = useState(false);
  const [printers,setPrinters]=useState<ReceiptPrinter[]>([]),[selected,setSelected]=useState<ReceiptPrinter|null>(null),[scanning,setScanning]=useState(false),[connecting,setConnecting]=useState(''),[scanMessage,setScanMessage]=useState('');
  useEffect(()=>{SecureStore.getItemAsync('receipt_printer').then((value)=>{if(value)try{setSelected(JSON.parse(value));}catch{}});},[]);
  const snap = data as Snapshot | null; const currency = snap?.restaurant.currencyCode;
  const scanPrinters=useCallback(async()=>{setScanning(true);setScanMessage('');try{const {discoverPrinters}=await import('../../services/printers');const result=await discoverPrinters();setPrinters(result.found);setScanMessage(result.errors.join('\n') || (!result.found.length ? 'No printers found. Turn on a BLE receipt printer or connect a USB printer through Android OTG.' : `${result.found.length} device(s) found.`));}catch(e){setScanMessage(messageOf(e));}finally{setScanning(false);}},[]);
  useEffect(()=>{if(Platform.OS!=='ios'&&!NativeModules.UniversalThermalUsb)return;const timer=setTimeout(()=>void scanPrinters(),0);return()=>clearTimeout(timer);},[scanPrinters]);
  async function connect(printer:ReceiptPrinter){setConnecting(printer.address);try{const {connectPrinter}=await import('../../services/printers');await connectPrinter(printer);setSelected(printer);Alert.alert('Printer connected',printer.name);}catch(e){Alert.alert('Could not connect',messageOf(e));}finally{setConnecting('');}}
  async function print() { if (!snap) return; try { if(selected){const {printToPrinter}=await import('../../services/printers');await printToPrinter(selected,[{type:'Init'},{type:'Align',value:'center'},{type:'Bold',value:true},{type:'Text',value:snap.restaurant.name},{type:'Bold',value:false},{type:'Text',value:snap.restaurant.address},{type:'Text',value:snap.restaurant.phone||''},{type:'Text',value:snap.number},{type:'Text',value:new Date(snap.at).toLocaleString()},{type:'Line',value:'-'},...snap.items.map((item)=>({type:'Text',value:`${item.quantity} x ${item.name}  ${money(item.quantity*Number(item.unitPrice),currency)}`})),{type:'Line',value:'-'},{type:'Text',value:`Subtotal  ${money(snap.totals.subtotal,currency)}`},{type:'Text',value:`Discount  ${money(snap.totals.discount,currency)}`},{type:'Text',value:`Tax  ${money(snap.totals.tax,currency)}`},{type:'Bold',value:true},{type:'Text',value:`TOTAL  ${money(snap.totals.total,currency)}`},{type:'Bold',value:false},{type:'Text',value:`Payment  ${snap.payment.method.replaceAll('_',' ')}`},{type:'Feed',value:3},{type:'Cut'}]);Alert.alert('Receipt sent',`Sent to ${selected.name}`);return;} const line = (label: string, value: string) => `<tr><td>${escapeHtml(label)}</td><td style="text-align:right">${escapeHtml(value)}</td></tr>`; const html = `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:Arial,sans-serif;color:#172923;padding:16px;max-width:360px;margin:auto}h2{margin-bottom:4px}table{width:100%;border-collapse:collapse}td{padding:7px 0;border-bottom:1px solid #ddd}small{color:#667971}@page{margin:12px}</style></head><body><h2>${escapeHtml(snap.restaurant.name)}</h2><small>${escapeHtml(snap.restaurant.address)}<br>${escapeHtml(snap.restaurant.phone)}<br>${escapeHtml(snap.number)}<br>${escapeHtml(new Date(snap.at).toLocaleString())}</small><table>${snap.items.map((item)=>line(`${item.quantity} Ã— ${item.name}`,money(item.quantity*Number(item.unitPrice),currency))).join('')}${line('Subtotal',money(snap.totals.subtotal,currency))}${line('Discount',money(snap.totals.discount,currency))}${line('Tax',money(snap.totals.tax,currency))}${line('Total',money(snap.totals.total,currency))}${line('Payment',snap.payment.method.replaceAll('_',' '))}</table></body></html>`; await Print.printAsync({ html }); } catch(e) { Alert.alert('Could not print',messageOf(e)); } }
  async function submitRefund() { setBusy(true); try { const receipt = await pos.receipts().then((all) => all.find((r) => r.id === id)); if (!receipt) throw new Error('Receipt not found'); await post(`/payments/${receipt.paymentId}/refunds`, { amount, reason, confirmed:true }); Alert.alert('Refund recorded', 'The refund is recorded in reports.'); setRefund(false); } catch(e) { Alert.alert('Refund failed',messageOf(e)); } finally { setBusy(false); } }
  return <Screen title="Receipt" back>{loading || error || !snap ? <State loading={loading} error={error} empty="Receipt unavailable" retry={refresh}/> : <><Card><Text style={{ color:colors.ink,fontSize:20,fontWeight:'700' }}>{snap.restaurant.name}</Text><Text style={{ color:colors.muted }}>{snap.restaurant.address}</Text><Text style={{ color:colors.muted }}>{snap.restaurant.phone}</Text><Text style={{ color:colors.muted }}>{snap.number}</Text><Text style={{ color:colors.muted }}>Order {snap.order.id.slice(0,8)} Â· {snap.employee.name}</Text><Text style={{ color:colors.muted }}>{new Date(snap.at).toLocaleString()}</Text></Card><Card><Section title="Items"/>{snap.items.map((item,i) => <Row key={i} title={`${item.quantity} Ã— ${item.name}`} right={<Text>{money(item.quantity * Number(item.unitPrice),currency)}</Text>}/>)}<Row title="Subtotal" right={<Text>{money(snap.totals.subtotal,currency)}</Text>}/><Row title="Discount" right={<Text>{money(snap.totals.discount,currency)}</Text>}/><Row title="Tax" right={<Text>{money(snap.totals.tax,currency)}</Text>}/><Row title="Total" right={<Text style={{ fontWeight:'700',fontSize:18 }}>{money(snap.totals.total,currency)}</Text>}/><Row title="Paid by" detail={snap.payment.method.replaceAll('_',' ')}/>{snap.payment.cashReceived && <Row title="Cash received" right={<Text>{money(snap.payment.cashReceived,currency)}</Text>}/ >}{snap.payment.changeDue && <Row title="Change" right={<Text>{money(snap.payment.changeDue,currency)}</Text>}/>}</Card><Card><Section title="Receipt printer"/><Button label="Find Bluetooth and USB printers" variant="secondary" loading={scanning} onPress={scanPrinters}/>{printers.map((printer)=><Button key={`${printer.type}:${printer.address}`} label={`${printer.name} (${printer.type.toUpperCase()})${selected?.address===printer.address ? ' âœ“' : ''}`} variant="text" loading={connecting===printer.address} onPress={()=>connect(printer)}/>)}<Text style={{color:colors.muted,fontSize:12}}>{scanMessage}</Text><Text style={{color:colors.muted,fontSize:12}}>{selected?`Selected: ${selected.name}`:'Select a printer for direct receipt printing. Bluetooth scan finds BLE printers; USB requires Android OTG.'}</Text></Card><Button label="Print receipt" icon="receipt" onPress={print}/><Button label="Done" variant="secondary" onPress={()=>router.replace('/(main)/orders')}/>{can('PROCESS_REFUND') && <Card>{refund ? <><Field label="Refund amount" value={amount} onChangeText={setAmount} keyboardType="decimal-pad"/><Field label="Reason" value={reason} onChangeText={setReason}/><Button label="Confirm refund" variant="danger" loading={busy} onPress={() => Alert.alert('Confirm refund?', `Record a refund of ${money(amount,currency)}?`, [{ text:'Cancel',style:'cancel' },{ text:'Confirm',style:'destructive',onPress:submitRefund }])}/></> : <Button label="Record refund" variant="secondary" onPress={() => setRefund(true)}/>}</Card>}</>}</Screen>;
}
