import { router, useLocalSearchParams } from 'expo-router';
import { useCallback, useState } from 'react';
import { Alert, Text, View } from 'react-native';
import { get, messageOf, patch, post, put, User } from '../../api/client';
import { pos, Receipt, Reservation, Summary, Table } from '../../api/pos';
import { useLive } from '../../hooks/useLive';
import { useAuth } from '../../store/auth';
import { Button, Card, Chip, Field, Row, Screen, Section, State, money } from '../../ui/Kit';
import { colors } from '../../theme/colors';

import { PhoneField } from '../../ui/PhoneField';
import { MenuManager } from '../../ui/MenuManager';

function Employees() {
  type TeamMember = User & { designation: string };
  const { data, loading, error, refresh } = useLive(useCallback(() => get<TeamMember[]>('/employees'), []), [] as TeamMember[]);
  const [form, setForm] = useState(false), [first, setFirst] = useState(''), [last, setLast] = useState(''), [email, setEmail] = useState(''), [phoneCountry,setPhoneCountry]=useState(''),[phone,setPhone]=useState(''),[designation, setDesignation] = useState(''), [busy, setBusy] = useState(false);
  async function create() { setBusy(true); try { const result = await post<{ user:User; initialPin:string }>('/employees', { firstName:first.trim(),lastName:last.trim(),email:email.trim() || null,phone:phone.trim() || null,phoneCountryCode:phoneCountry || undefined,designation:designation.trim(),role:'WAITER' }); Alert.alert('Employee created', `Username: ${result.user.username}\nInitial PIN: ${result.initialPin}\nShare this PIN privately. It is shown only once.`); setForm(false); setFirst(''); setLast(''); setEmail('');setPhone('');setPhoneCountry(''); setDesignation(''); await refresh(); } catch(e) { Alert.alert('Could not create employee',messageOf(e)); } finally { setBusy(false); } }
  return <><Button label={form ? 'Close form' : 'Add employee'} icon="plus" variant="secondary" onPress={()=>setForm(!form)}/>{form && <Card><Field label="First name" value={first} onChangeText={setFirst}/><Field label="Last name" value={last} onChangeText={setLast}/><Field label="Email (optional)" value={email} onChangeText={setEmail} keyboardType="email-address"/><PhoneField label="Mobile number" optional countryCode={phoneCountry} onCountryChange={setPhoneCountry} number={phone} onNumberChange={setPhone}/><Field label="Designation" value={designation} onChangeText={setDesignation} placeholder="Type any job title" autoCapitalize="words" maxLength={255}/><Text style={{color:colors.muted,fontSize:12}}>New employees start with waiter access. You can change access in the team list.</Text><Button label="Create employee" loading={busy} disabled={!first.trim() || !last.trim() || !designation.trim()} onPress={create}/></Card>}
  {loading || error || !data.length ? <State loading={loading} error={error} empty="No team members yet." retry={refresh}/> : data.map((u)=><Card key={u.id}><Row title={`${u.firstName} ${u.lastName}`} detail={`${u.designation} · ${u.username} · ${u.active === false ? 'Inactive' : 'Active'}`}/><Text style={{color:colors.muted,fontSize:12}}>Access role: {u.role}</Text><View style={{flexDirection:'row',flexWrap:'wrap',gap:6}}>{['MANAGER','CASHIER','WAITER','KITCHEN'].map((r)=><Chip key={r} label={r} selected={u.role===r} onPress={()=>{if(u.role===r)return;Alert.alert('Change role?',`${u.firstName} will have ${r.toLowerCase()} permissions.`,[{text:'Cancel',style:'cancel'},{text:'Change',onPress:async()=>{try{await patch(`/employees/${u.id}`,{role:r});await refresh();}catch(e){Alert.alert('Failed',messageOf(e));}}}]);}}/>)}</View><View style={{ flexDirection:'row',gap:8 }}><View style={{ flex:1 }}><Button label="Reset PIN" variant="secondary" onPress={()=>Alert.alert('Reset PIN?',`This will replace the PIN for ${u.firstName}.`,[{text:'Cancel',style:'cancel'},{text:'Reset',onPress:async()=>{try{const result=await post<{initialPin:string}>(`/employees/${u.id}/reset-pin`);Alert.alert('New PIN',result.initialPin);}catch(e){Alert.alert('Failed',messageOf(e));}}}])}/></View><View style={{ flex:1 }}><Button label={u.active === false ? 'Activate' : 'Deactivate'} variant="secondary" onPress={async()=>{try{await patch(`/employees/${u.id}`,{active:u.active===false});await refresh();}catch(e){Alert.alert('Failed',messageOf(e));}}}/></View></View></Card>)}</>;
}
function Reservations() {
  const { data, loading, error, refresh } = useLive(useCallback(() => pos.reservations(), []), [] as Reservation[]);
  const { data: tables } = useLive(useCallback(() => pos.tables(), []), [] as Table[]);
  const [name,setName]=useState(''),[phoneCountry,setPhoneCountry]=useState(''),[phone,setPhone]=useState(''),[guests,setGuests]=useState('2'),[date,setDate]=useState(''),[table,setTable]=useState(''),[busy,setBusy]=useState(false);
  async function create(){setBusy(true);try{const startAt=new Date(date);if(isNaN(startAt.getTime()))throw new Error('Enter a valid date and time, such as 2026-10-02T19:00');await pos.addReservation({customerName:name.trim(),phone:phone.trim() || null,phoneCountryCode:phoneCountry || undefined,guestCount:Number(guests),startAt:startAt.toISOString(),...(table?{tableId:table}:{})});setName('');setPhone('');setPhoneCountry('');setDate('');setTable('');await refresh();}catch(e){Alert.alert('Could not reserve',messageOf(e));}finally{setBusy(false);}}
  return <><Card><Section title="New reservation"/><Field label="Guest name" value={name} onChangeText={setName}/><PhoneField label="Mobile number" optional countryCode={phoneCountry} onCountryChange={setPhoneCountry} number={phone} onNumberChange={setPhone}/><Field label="Guests" value={guests} onChangeText={setGuests} keyboardType="numeric"/><Field label="Date and time (YYYY-MM-DDTHH:mm)" value={date} onChangeText={setDate} placeholder="2026-10-02T19:00"/><Text style={{color:colors.muted}}>Assign a table (optional)</Text>{tables.map((t)=><Chip key={t.id} label={`Table ${t.tableNumber}`} selected={table===t.id} onPress={()=>setTable(table===t.id?'':t.id)}/>)}<Button label="Save reservation" disabled={!name||!date} loading={busy} onPress={create}/></Card>
    <Section title="Upcoming reservations"/>{loading||error||!data.length?<State loading={loading} error={error} empty="No reservations yet." retry={refresh}/>:data.map((r)=><Card key={r.id}><Row title={r.customerName} detail={`${r.guestCount} guests Ã‚Â· ${new Date(r.startAt).toLocaleString()}`} right={<Chip label={r.status}/>}/><View style={{flexDirection:'row',gap:8}}>{r.tableId && ['PENDING','CONFIRMED'].includes(r.status) && <View style={{flex:1}}><Button label="Seat" variant="secondary" onPress={async()=>{try{const result=await pos.seat(r.id);router.push(`/order/${result.order.id}`);}catch(e){Alert.alert('Could not seat',messageOf(e));}}}/></View>}{['PENDING','CONFIRMED'].includes(r.status)&&<View style={{flex:1}}><Button label="Cancel" variant="text" onPress={async()=>{try{await pos.editReservation(r.id,{status:'CANCELLED'});await refresh();}catch(e){Alert.alert('Failed',messageOf(e));}}}/></View>}</View></Card>)}</>;
}
function Receipts() { const {data,loading,error,refresh}=useLive(useCallback(() => pos.receipts(), []),[] as Receipt[]); return <>{loading||error||!data.length?<State loading={loading} error={error} empty="No receipts yet." retry={refresh}/>:data.map((r)=><Card key={r.id}><Row title={r.number} detail={new Date(r.createdAt).toLocaleString()} icon="receipt" onPress={()=>router.push(`/receipt/${r.id}`)}/></Card>)}</>; }
function Reports() {
  const [from,setFrom]=useState(()=>new Date(new Date().setDate(new Date().getDate()-7)).toISOString().slice(0,10)),[to,setTo]=useState(()=>new Date().toISOString().slice(0,10));
  const [data,setData]=useState<Summary|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''); const currency=useAuth((s)=>s.me?.restaurant.currencyCode);
  async function load(){setBusy(true);setError('');try{setData(await pos.report(new Date(`${from}T00:00:00`).toISOString(),new Date(`${to}T23:59:59`).toISOString()));}catch(e){setError(messageOf(e));}finally{setBusy(false);}}
  return <><Card><Field label="From (YYYY-MM-DD)" value={from} onChangeText={setFrom}/><Field label="To (YYYY-MM-DD)" value={to} onChangeText={setTo}/><Button label="View report" loading={busy} onPress={load}/></Card>{error&&<State error={error} retry={load}/ >}{data&&<Card><Row title="Gross sales" right={<Text>{money(data.grossSales,currency)}</Text>}/><Row title="Refunds" right={<Text>{money(data.refunds,currency)}</Text>}/><Row title="Net sales" right={<Text style={{fontWeight:'700'}}>{money(data.netSales,currency)}</Text>}/><Row title="Completed orders" right={<Text>{data.completedOrders}</Text>}/></Card>}</>;
}
type Restaurant = {name:string;businessType:string;address:string;city:string;state:string;postalCode:string;phone:string;countryCode:string;timezone:string};
type Setting = { key: string; value: unknown };
function Settings() {
  const {data,loading,error,refresh}=useLive(useCallback(()=>get<Restaurant>('/restaurants/me'),[]),null as Restaurant|null,false);
  const {data:settings,refresh:refreshSettings}=useLive(useCallback(()=>get<Setting[]>('/settings'),[]),[] as Setting[],false);
  const [form,setForm]=useState<Partial<Restaurant> & {phoneCountryCode?:string}>({}),[methods,setMethods]=useState<string[]|null>(null),[busy,setBusy]=useState(false);
  const enabled = methods ?? (settings.find((s)=>s.key==='enabledPaymentMethods')?.value as string[]|undefined) ?? ['CASH','CARD_MANUAL','UPI_MANUAL','OTHER'];
  async function save(){setBusy(true);try{if(Object.keys(form).length) await patch('/restaurants/me',form);if(methods) await put('/settings/enabledPaymentMethods',{value:methods});setForm({});setMethods(null);await Promise.all([refresh(),refreshSettings()]);Alert.alert('Saved','Restaurant settings updated.');}catch(e){Alert.alert('Update failed',messageOf(e));}finally{setBusy(false);}}
  return <>{loading||error||!data?<State loading={loading} error={error} empty="Restaurant settings unavailable" retry={refresh}/>:<><Card><Section title="Restaurant profile"/>{(['name','businessType','address','city','state','postalCode','timezone'] as const).map((key)=><Field key={key} label={key.replace(/([A-Z])/g,' $1')} value={form[key]??data[key]??''} onChangeText={(v)=>setForm((old)=>({...old,[key]:v}))}/>)}<PhoneField label="Mobile number" optional countryCode={form.phoneCountryCode??data.countryCode} onCountryChange={(v)=>setForm((old)=>({...old,phoneCountryCode:v,phone:""}))} number={form.phone??data.phone??""} onNumberChange={(v)=>setForm((old)=>({...old,phone:v,phoneCountryCode:old.phoneCountryCode??data.countryCode}))}/></Card><Card><Section title="Payment methods"/><Text style={{color:colors.muted}}>Choose the methods staff can confirm manually.</Text>{['CASH','CARD_MANUAL','UPI_MANUAL','OTHER'].map((method)=><Chip key={method} label={method.replaceAll('_',' ')} selected={enabled.includes(method)} onPress={()=>setMethods(enabled.includes(method)?enabled.filter((v)=>v!==method):[...enabled,method])}/>)}</Card><Card><Section title="Tax"/><Text style={{color:colors.muted}}>Set tax percentages on each menu item.</Text><Button label="Edit menu taxes" variant="secondary" onPress={()=>router.push('/manage/menu')}/></Card><Button label="Save settings" disabled={!Object.keys(form).length&&!methods} loading={busy} onPress={save}/></>}</>;
}
function Profile() { const {me}=useAuth();return <Card><Row title="Name" detail={`${me?.user.firstName} ${me?.user.lastName}`}/><Row title="Username" detail={me?.user.username}/><Row title="Role" detail={me?.user.role}/><Row title="Restaurant" detail={me?.restaurant.name}/></Card>; }
export default function ManageSection() { const {section}=useLocalSearchParams<{section:string}>();const titles:Record<string,string>={menu:'Menu & categories',employees:'Team',reservations:'Reservations',receipts:'Receipts',reports:'Reports',settings:'Settings',profile:'Profile'};return <Screen title={titles[section]||'Manage'} back>{section==='menu'?<MenuManager/>:section==='employees'?<Employees/>:section==='reservations'?<Reservations/>:section==='receipts'?<Receipts/>:section==='reports'?<Reports/>:section==='settings'?<Settings/>:section==='profile'?<Profile/>:<State empty="Section not found"/>}</Screen>; }
